### ISSUE TITLE
Add YAML support

### ISSUE THREAD

**Issue by myishay** [PerimeterX/marshmallow#11]
This project looks cool!
It would be really helpful if I could natively use it for YAML files too 😁

**Comment by SkyDiverCool** [comment]
For that there needs to be a yaml lexer brought in or implemented(then also actively maintained by someone).

Also there's the whole question about the feature scope of the library, because if you bring in Yaml you also gotta support toml and pretty much all other "unstructured structured" formats(would love to see CBOR personally). Which then leads to the fact that all of them have to be maintained by someone (open source maintainers come and go all the time and the original implementer might not stick for a while but others will be left with the code)

**Comment by avivpxi** [comment]
@myishay the way I see it there are two options, complying with what @SkyDiverCool suggested:
1. We implement or use an existing implementation of a yaml lexer - in order to be performant, marshmallow uses a [dedicated lexer](https://github.com/PerimeterX/marshmallow/blob/main/unmarshal.go#L59) to allow us to perform a single pass iteration over the data. This is the best alternative as it will be the most native one and the most performant one. However, as @SkyDiverCool suggested, it would be a lot of code to maintain unless we find an existing solution like we've done with jlexer in the JSON use case.
2. If you're not heavily concerned with performance, you could always use the fact that marshmallow also supports accepting an already unmarshaled map - [playground example](https://go.dev/play/p/DYFf_hIPpE_M). I'm doing a tiny trick there since `UnmarshalFromJSONMap` expects all numeric values to be of type `float64` so I added decimal points to the numbers in the input yaml (otherwise `gopkg.in/yaml.v3` parses them as ints) but we can easily add `int` support to `UnmarshalFromJSONMap` to solve this issue.
The question, @myishay - is which one of these alternatives seems more reasonable?

@SkyDiverCool in the case of CBOR, I guess it would make no sense to go to the second alternative since it's all about performance. I would love to see an implementation such a lexer and to bring this kind of support into marshmallow, this could tremendously boost performance, could it?

**Comment by avivpxi** [comment]
Closing due to no response from participants
